project:
  type: book
  output-dir: docs
  execute-dir: file

book:
  title: "Geographic Data Science with Python"
  author:
    - "Sergio J. Rey"
    - "Dani Arribas-Bel"
    - "Levi J. Wolf"
  date: "2020"
  favicon: favicon.ico
  cover-image: logo.png
  repo-url: https://github.com/gdsbook/book
  repo-branch: master
  site-url: https://geographicdata.science/book
  chapters:
    - index.qmd
    - part: "Preface"
      chapters:
        - notebooks/00_toc.qmd
    - part: intro_part_i.qmd
      chapters:
        - notebooks/01_geo_thinking.qmd
        - notebooks/02_geospatial_computational_environment.qmd
        - notebooks/03_spatial_data.qmd
        - notebooks/04_spatial_weights.qmd
    - part: intro_part_ii.qmd
      chapters:
        - notebooks/05_choropleth.qmd
        - notebooks/06_spatial_autocorrelation.qmd
        - notebooks/07_local_autocorrelation.qmd
        - notebooks/08_point_pattern_analysis.qmd
    - part: intro_part_iii.qmd
      chapters:
        - notebooks/09_spatial_inequality.qmd
        - notebooks/10_clustering_and_regionalization.qmd
        - notebooks/11_regression.qmd
        - notebooks/12_feature_engineering.qmd
    - part: "Endmatter"
      chapters:
        - notebooks/references.qmd
    - part: "Datasets"
      chapters:
        - data/README.qmd
        - data/airbnb/regression_cleaning.qmd
        - data/airports/airports_cleaning.qmd
        - data/brexit/brexit_cleaning.qmd
        - data/countries/countries_cleaning.qmd
        - data/ghsl/build_ghsl_extract.qmd
        - data/h3_grid/build_sd_h3_grid.qmd
        - data/mexico/README.qmd
        - data/nasadem/build_nasadem_sd.qmd
        - data/sandiego/sandiego_tracts_cleaning.qmd
        - data/texas/README.qmd
        - data/tokyo/tokyo_cleaning.qmd
        - data/us_county_income/README.qmd

bibliography: notebooks/references.bib

jupyter: gds

execute:
  freeze: auto

format:
  html:
    theme:
      - litera
    toc: true
    code-fold: false
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 900px
  pdf:
    documentclass: krantz
    pdf-engine: tectonic
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
