---
title: "Part I — Building Blocks"
---

## Overview

Geography is a longstanding academic discipline, so why do we need fancy new concepts, methods, and algorithms? Indeed, why is this book about geographic *data science* and not some other kind of quantitative study in geography, such as *geocomputation* or *Geographic Information Science*? This section addresses these questions by outlining the conceptual and practical fundamentals of *geographic data science*, as well as a few of the innovations and important new frames of reference that make geographic data science distinct from its precursors.

First, in [Chapter 1](notebooks/01_geo_thinking.qmd), we outline the fundamentals of geographic theory for data scientists. The main distinctions between geographic *models* and the *data structures* that represent them are explained, and the linkages between these models and structures are also discussed. In [Chapter 2](notebooks/02_geospatial_computational_environment.qmd), we discuss the fundamental differences in how data science is *done*: reproducible, literate and interactive programming environments have seriously changed the game for how analysis is done. Then, starting in [Chapter 3](notebooks/03_spatial_data.qmd), we show how these notions translate into patterns to read/write/represent geographic data formats. Finally, we close this part in [Chapter 4](notebooks/04_spatial_weights.qmd) by discussing how to represent and store geographical relationships in an efficient data structure. Together, this provides a comprehensive overview of the main models of geographical processes, as well as the nuts and bolts of how to interact with geographical data.
