---
title: H3 Grid
jupyter: python3
---

## Build a `H3` grid for the San Diego region


```{python}
#| echo: false
from IPython.display import display_markdown

display_markdown(open("README.md").read(), raw=True)
```

## Infrastructure

To create a container that includes `h3` save the following on a file called `Dockerfile`:

```Dockerfile
FROM darribas/gds_dev:4.1

USER root
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add - \
 && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' \
 && apt-get update \
 && apt-get install --yes cmake
USER $NB_UID
RUN pip install h3
```

And build the container by running the following from the same folder where the file is stored:

```
docker build -t gds_h3 .
```

When if finishes, you should be able to launch the `gds_h3` container and run this notebook from there.

```{python}
%matplotlib inline

from h3 import h3
import geopandas
from shapely.geometry import Polygon
import contextily as ctx
import cenpy
```

## Region to cover

```{python}
sd = geopandas.read_file("sd_city_centre.geojson")
ax = sd.plot(alpha=0.25, color="orange", figsize=(9, 9))
ctx.add_basemap(ax, crs=sd.crs.to_string())
```

## Build H3 geography

```{python}
%time hexs = h3.polyfill(sd.geometry[0].__geo_interface__, 8, geo_json_conformant = True)
```

```{python}
polygonise = lambda hex_id: Polygon(
                                h3.h3_to_geo_boundary(
                                    hex_id, geo_json=True)
                                    )

%time all_polys = geopandas.GeoSeries(list(map(polygonise, hexs)), \
                                      index=hexs, \
                                      crs="EPSG:4326" \
                                     )
```

```{python}
ax = all_polys.plot(alpha=0.5, color="xkcd:pale yellow", figsize=(9, 9))
ctx.add_basemap(ax, crs=all_polys.crs.to_string())
ax.set_title(f"{all_polys.shape[0]} Hexagons");
```

## Clip ocean out

There are quite a few hexagons that fall within the ocean. Let's get rid of them. For that, we will pull down the polygon for San Diego county using `cenpy`:

```{python}
census = cenpy.Decennial2010()
tracts = census.from_msa("San Diego, CA", level="tract")
```

Now these geometries include also some ocean:

```{python}
ax = tracts.plot(alpha=0.5, color="xkcd:pale green")
ctx.add_basemap(ax, crs=tracts.crs.to_string())
```

It turns out that part is a separate polygon that may be removed easily:

```{python}
tracts.head()
```

```{python}
tracts_land_one = geopandas.GeoDataFrame(
                        {"geometry": [tracts.query("GEOID != '06073990100'").unary_union],
                         "id": ["one"]
                        }, crs=tracts.crs)
```

```{python}
ax = tracts_land_one.to_crs(epsg=4269).plot()
all_polys.to_crs(epsg=4269).plot(color="xkcd:pale yellow", ax=ax)
```

Let's convert `all_polys` into a `GeoDataFrame`:

```{python}
h3_all = geopandas.GeoDataFrame({"geometry": all_polys,
                                 "hex_id": all_polys.index},
                                crs=all_polys.crs
                               )
```

We're an overlay away from our target:

```{python}
%%time
h3_land = geopandas.overlay(h3_all, 
                            tracts_land_one.to_crs(h3_all.crs), 
                            how="intersection"
                           )
```

```{python}
ax = h3_land.plot(alpha=0.5, color="xkcd:pale yellow")
ctx.add_basemap(ax, crs=h3_land.crs.to_string())
```

## Write out to `GPKG`

```{python}
! rm sd_h3_grid.gpkg
h3_land.drop("id", axis=1).to_file("sd_h3_grid.gpkg", driver="GPKG")
```

## Tract Vs H3 geographies

Get tracts only within the grid:

```{python}
shp = geopandas.GeoDataFrame(
    {"geometry": [h3_land.unary_union],
     "id": ["one"]
    }, crs = h3_land.crs).to_crs(tracts.crs)
sub = geopandas.overlay(tracts, shp, how="intersection")
```

Compare:

```{python}
ax = sub.plot(facecolor="k", edgecolor="xkcd:lilac", figsize=(9, 9))
h3_land.to_crs(sub.crs).plot(facecolor="none", linewidth=0.5, edgecolor="xkcd:light aqua", ax=ax)
ctx.add_basemap(ax, crs=sub.crs.to_string())
```

---

## Download link

{download}`[Download the *sd_h3_grid.gpkg* file] <sd_h3_grid.gpkg>`

